services:
  dataomnifrontend:
    image: ghcr.io/the-data-omni/dataomnifrontend:latest  # Pulls from GHCR
    restart: always
    ports:
      - "8080:8080"
    environment:
      - VITE_APP_URL=
      - VITE_LOG_LEVEL=
      - VITE_AUTH_STRATEGY=
      - VITE_AUTH0_DOMAIN=
      - VITE_AUTH0_CLIENT_ID=
      - VITE_CLERK_PUBLISHABLE_KEY=
      - VITE_COGNITO_AUTHORITY=
      - VITE_COGNITO_DOMAIN=
      - VITE_COGNITO_CLIENT_ID=
      - VITE_SUPABASE_URL=
      - VITE_SUPABASE_PUBLIC_KEY=
      - VITE_MAPBOX_API_KEY=
      - VITE_GOOGLE_TAG_MANAGER_ID=
  schemascoring_api:
    image: ghcr.io/the-data-omni/schemascoring_api:latest  # Pulls from GHCR
    restart: always
    ports:
      - "5001:5000"
  dataomni_api:
    image: ghcr.io/the-data-omni/dataomni_api:latest  # Pulls from GHCR
    restart: always
    ports:
      - "5001:5000"
    environment:
      - OPENAI_API_KEY=''